import { DiagnosticService, HealthPackage, Testimonial } from './types';

export const DIAGNOSTIC_SERVICES: DiagnosticService[] = [
  // --- GENERAL ULTRASOUND (USG) ---
  {
    id: 'scan-usg-whole-abd-pelvis',
    name: 'Whole Abdomen/Pelvis + Abdomen',
    category: 'scan',
    subCategory: 'General Sonography',
    price: 2500,
    discountPrice: 1300,
    description: 'Detailed USG examination of upper & lower abdominal organs, pelvic structures, kidneys, liver, gallbladder, and urinary tract.',
    preparation: 'Overnight or 6 hours fasting mandatory. Full bladder required.',
    duration: '15-20 mins',
    reportDelivery: 'Immediate (within 1 hour)',
    popular: true
  },
  {
    id: 'scan-usg-upper-abd-kub',
    name: 'Upper Abdomen/Pelvis/KUB',
    category: 'scan',
    subCategory: 'General Sonography',
    price: 2000,
    discountPrice: 1000,
    description: 'Ultrasound screening of upper abdomen organs, liver, kidneys, ureters, and bladder (KUB).',
    preparation: 'Fasting 6 hours mandatory. Full bladder required for KUB evaluation.',
    duration: '15 mins',
    reportDelivery: 'Immediate (within 1 hour)',
    popular: true
  },
  {
    id: 'scan-usg-pelvis-ta-tvs',
    name: 'USG Pelvis (TA & TVS)',
    category: 'scan',
    subCategory: 'General Sonography',
    price: 2000,
    discountPrice: 1000,
    description: 'Transabdominal and Transvaginal ultrasound for in-depth evaluation of uterus, ovaries, and pelvic anatomy.',
    preparation: 'Full bladder required for TA scan. Empty bladder for TVS scan.',
    duration: '15-20 mins',
    reportDelivery: 'Immediate (within 1 hour)',
    popular: true
  },
  {
    id: 'scan-usg-neck',
    name: 'USG Neck',
    category: 'scan',
    subCategory: 'General Sonography',
    price: 2500,
    discountPrice: 1300,
    description: 'Ultrasound imaging of neck structures including thyroid gland, parotid, submandibular glands, and cervical lymph nodes.',
    preparation: 'No fasting required. Avoid wearing neck jewelry.',
    duration: '15 mins',
    reportDelivery: 'Immediate (within 1 hour)'
  },
  {
    id: 'scan-usg-scrotum',
    name: 'USG Scrotum',
    category: 'scan',
    subCategory: 'General Sonography',
    price: 2500,
    discountPrice: 1300,
    description: 'High-frequency ultrasound evaluation of testes, epididymis, and scrotal tissues for varicoceles, hydroceles, or lesions.',
    preparation: 'No fasting required.',
    duration: '15 mins',
    reportDelivery: 'Immediate (within 1 hour)'
  },
  {
    id: 'scan-usg-breast-unilateral',
    name: 'USG Breast (Unilateral)',
    category: 'scan',
    subCategory: 'General Sonography',
    price: 2800,
    discountPrice: 1500,
    description: 'Focused ultrasound scan of single breast tissue and axillary lymph nodes to evaluate lumps, cysts, or localized pain.',
    preparation: 'No talcum powder or lotion on skin on scan day.',
    duration: '15 mins',
    reportDelivery: 'Immediate (within 1 hour)'
  },
  {
    id: 'scan-usg-breast-bilateral',
    name: 'USG Breast (Bilateral)',
    category: 'scan',
    subCategory: 'General Sonography',
    price: 3800,
    discountPrice: 2000,
    description: 'Complete high-resolution ultrasound screening of both breasts and axillae for cyst, fibroadenoma, or tissue assessment.',
    preparation: 'Do not apply powders or deodorants on chest area.',
    duration: '20 mins',
    reportDelivery: 'Immediate (within 1 hour)',
    popular: true
  },
  {
    id: 'scan-usg-small-part-unilateral',
    name: 'USG Small Part (Unilateral)/Local Part/Chest',
    category: 'scan',
    subCategory: 'General Sonography',
    price: 2500,
    discountPrice: 1300,
    description: 'High-frequency superficial tissue or localized part ultrasound (chest wall, lipoma, swelling, or single site organ).',
    preparation: 'No special preparation needed.',
    duration: '15 mins',
    reportDelivery: 'Immediate (within 1 hour)'
  },
  {
    id: 'scan-usg-local-part-bilateral',
    name: 'USG Local Part (Bilateral)',
    category: 'scan',
    subCategory: 'General Sonography',
    price: 3500,
    discountPrice: 2000,
    description: 'Bilateral superficial tissue scan covering paired local body regions or structures.',
    preparation: 'No special preparation needed.',
    duration: '20 mins',
    reportDelivery: 'Immediate (within 1 hour)'
  },
  {
    id: 'scan-usg-articular-msk',
    name: 'Articular joints/MSK joints',
    category: 'scan',
    subCategory: 'General Sonography',
    price: 2800,
    discountPrice: 1500,
    description: 'Musculoskeletal ultrasound scan evaluating joint cartilage, tendons, ligaments, synovium, and soft tissue fluid collections.',
    preparation: 'No fasting required.',
    duration: '15-20 mins',
    reportDelivery: 'Immediate (within 1 hour)'
  },

  // --- OBSTETRICS SCANS ---
  {
    id: 'scan-obs-1st-trimester',
    name: '1st Trimester',
    category: 'scan',
    subCategory: 'Obstetric Sonography',
    price: 2200,
    discountPrice: 1200,
    description: 'Early pregnancy ultrasound to confirm intrauterine viability, gestational age, cardiac activity, and single/twin pregnancy.',
    preparation: 'Moderate full bladder required.',
    duration: '15 mins',
    reportDelivery: 'Immediate (within 1 hour)',
    popular: true
  },
  {
    id: 'scan-obs-2nd-trimester',
    name: '2nd Trimester',
    category: 'scan',
    subCategory: 'Obstetric Sonography',
    price: 2200,
    discountPrice: 1200,
    description: 'Routine second trimester fetal growth evaluation, placenta location, and amniotic fluid check.',
    preparation: 'No fasting required.',
    duration: '15-20 mins',
    reportDelivery: 'Immediate (within 1 hour)'
  },
  {
    id: 'scan-obs-routine-trimester',
    name: 'Routine Trimester',
    category: 'scan',
    subCategory: 'Obstetric Sonography',
    price: 2200,
    discountPrice: 1200,
    description: 'Regular antenatal growth and wellbeing scan monitoring fetal parameters, weight estimate, and liquor level.',
    preparation: 'No fasting required.',
    duration: '15 mins',
    reportDelivery: 'Immediate (within 1 hour)'
  },
  {
    id: 'scan-obs-3d-pregnancy',
    name: '3D Pregnancy',
    category: 'scan',
    subCategory: 'Obstetric Sonography',
    price: 3600,
    discountPrice: 2000,
    description: 'Advanced 3D surface rendering volumetric ultrasound of fetus providing realistic facial and physical anatomical visualization.',
    preparation: 'No fasting required. Stay hydrated.',
    duration: '20-25 mins',
    reportDelivery: 'Immediate (within 1 hour)'
  },
  {
    id: 'scan-obs-nt-scan',
    name: 'NT Scan',
    category: 'scan',
    subCategory: 'Obstetric Sonography',
    price: 3600,
    discountPrice: 2000,
    description: 'Specialized 11-13.6 week pregnancy scan measuring nuchal translucency and nasal bone for chromosomal abnormality screening.',
    preparation: 'Moderately full bladder.',
    duration: '20-30 mins',
    reportDelivery: 'Immediate (within 1 hour)',
    popular: true
  },
  {
    id: 'scan-obs-anomaly-scan',
    name: 'Anomaly Scan',
    category: 'scan',
    subCategory: 'Obstetric Sonography',
    price: 4500,
    discountPrice: 2500,
    description: 'Comprehensive detailed level-II anatomical scan done at 18-22 weeks to evaluate organ structures, spine, heart, brain, and limbs.',
    preparation: 'No fasting. Eat light meal before scan.',
    duration: '30-40 mins',
    reportDelivery: 'Immediate (within 1 hour)',
    popular: true
  },
  {
    id: 'scan-obs-follicular-single',
    name: 'Follicular Study (Single)',
    category: 'scan',
    subCategory: 'Obstetric Sonography',
    price: 1000,
    discountPrice: 500,
    description: 'Single TVS ultrasound visit to measure ovarian follicle growth, endometrial thickness, and ovulation tracking.',
    preparation: 'Empty bladder before procedure.',
    duration: '10 mins',
    reportDelivery: 'Immediate (within 30 mins)'
  },
  {
    id: 'scan-obs-follicular-package',
    name: 'Follicular Study (Package)',
    category: 'scan',
    subCategory: 'Obstetric Sonography',
    price: 3600,
    discountPrice: 2000,
    description: 'Package covering multiple serial TVS ultrasound visits throughout menstrual cycle to track follicle maturation and ovulation day.',
    preparation: 'Empty bladder before each visit.',
    duration: 'Multiple sittings',
    reportDelivery: 'Cumulative Report',
    popular: true
  },
  {
    id: 'scan-obs-twins-pregnancy',
    name: 'Twins Scan (Pregnancy)',
    category: 'scan',
    subCategory: 'Obstetric Sonography',
    price: 3600,
    discountPrice: 2000,
    description: 'Specialized antenatal ultrasound growth evaluation for twin (multiple) gestations.',
    preparation: 'No fasting required.',
    duration: '25 mins',
    reportDelivery: 'Immediate (within 1 hour)'
  },
  {
    id: 'scan-obs-twins-anomaly',
    name: 'Twins Scan (Anomaly)',
    category: 'scan',
    subCategory: 'Obstetric Sonography',
    price: 6000,
    discountPrice: 3500,
    description: 'Detailed level-II anomaly scan evaluating complete anatomical organ structures for twin fetuses.',
    preparation: 'No fasting required.',
    duration: '45 mins',
    reportDelivery: 'Immediate (within 1 hour)'
  },

  // --- DOPPLER SCANS ---
  {
    id: 'scan-doppler-scrotal',
    name: 'Scrotal Doppler',
    category: 'scan',
    subCategory: 'Color Doppler Sonography',
    price: 3600,
    discountPrice: 2000,
    description: 'Color Doppler ultrasound measuring blood vascular flow in testicular arteries/veins for varicocele, torsion, or ischemia.',
    preparation: 'No fasting required.',
    duration: '20 mins',
    reportDelivery: 'Immediate (within 1 hour)'
  },
  {
    id: 'scan-doppler-small-part',
    name: 'Small Part',
    category: 'scan',
    subCategory: 'Color Doppler Sonography',
    price: 3200,
    discountPrice: 1800,
    description: 'Vascular Doppler study for localized superficial mass, tissue inflammation, or thyroid/gland blood flow.',
    preparation: 'No special preparation.',
    duration: '15-20 mins',
    reportDelivery: 'Immediate (within 1 hour)'
  },
  {
    id: 'scan-doppler-renal',
    name: 'Renal Doppler',
    category: 'scan',
    subCategory: 'Color Doppler Sonography',
    price: 4500,
    discountPrice: 2500,
    description: 'Renal artery Color Doppler to diagnose renal artery stenosis, renovascular hypertension, or transplant kidney perfusion.',
    preparation: 'Strict 6-8 hours fasting required.',
    duration: '25 mins',
    reportDelivery: 'Immediate (within 1 hour)',
    popular: true
  },
  {
    id: 'scan-doppler-neck-carotid',
    name: 'Neck/Carotid Doppler',
    category: 'scan',
    subCategory: 'Color Doppler Sonography',
    price: 3600,
    discountPrice: 2000,
    description: 'Color Doppler assessment of carotid and vertebral arteries to screen stroke risk, plaque, and vessel stenosis.',
    preparation: 'No neck accessories or high collar clothing.',
    duration: '20 mins',
    reportDelivery: 'Immediate (within 1 hour)',
    popular: true
  },
  {
    id: 'scan-doppler-obstetric',
    name: 'Obstetric Doppler',
    category: 'scan',
    subCategory: 'Color Doppler Sonography',
    price: 3200,
    discountPrice: 1800,
    description: 'Umbilical, Uterine, and Middle Cerebral Artery (MCA) Doppler evaluating fetoplacental blood circulation and IUGR.',
    preparation: 'No fasting required.',
    duration: '20 mins',
    reportDelivery: 'Immediate (within 1 hour)',
    popular: true
  },
  {
    id: 'scan-doppler-artery-venous-unilateral',
    name: 'Artery/Venous Doppler (Unilateral)',
    category: 'scan',
    subCategory: 'Color Doppler Sonography',
    price: 3600,
    discountPrice: 2000,
    description: 'Color Doppler examination of arterial OR venous system of single upper or lower limb.',
    preparation: 'Wear loose clothing.',
    duration: '20-30 mins',
    reportDelivery: 'Immediate (within 1 hour)'
  },
  {
    id: 'scan-doppler-artery-venous-bilateral',
    name: 'Artery/Venous Doppler (Bilateral)',
    category: 'scan',
    subCategory: 'Color Doppler Sonography',
    price: 6000,
    discountPrice: 3500,
    description: 'Color Doppler study of arterial OR venous flow in both legs or arms.',
    preparation: 'Wear loose clothing.',
    duration: '35-45 mins',
    reportDelivery: 'Immediate (within 1 hour)'
  },
  {
    id: 'scan-doppler-art-ven-unilateral',
    name: 'Artery + Venous Doppler (Unilateral)',
    category: 'scan',
    subCategory: 'Color Doppler Sonography',
    price: 6500,
    discountPrice: 3800,
    description: 'Combined arterial AND venous vascular Doppler evaluation of single upper or lower limb.',
    preparation: 'Wear comfortable loose clothing.',
    duration: '30-40 mins',
    reportDelivery: 'Immediate (within 1 hour)'
  },
  {
    id: 'scan-doppler-art-ven-bilateral',
    name: 'Artery + Venous Doppler (Bilateral)',
    category: 'scan',
    subCategory: 'Color Doppler Sonography',
    price: 12000,
    discountPrice: 7000,
    description: 'Full comprehensive combined arterial AND venous Color Doppler scan of both upper or lower limbs.',
    preparation: 'Wear loose clothing.',
    duration: '50-60 mins',
    reportDelivery: 'Immediate (within 1 hour)',
    popular: true
  },

  // --- ECHO (CARDIOLOGY) ---
  {
    id: 'scan-echo-2d',
    name: '2D-ECHO',
    category: 'scan',
    subCategory: 'ECHO (Cardiac Sonography)',
    price: 4000,
    discountPrice: 2200,
    description: '2D Echocardiogram with Color Doppler evaluating heart chamber dimensions, valve function, wall motion, and Ejection Fraction.',
    preparation: 'No fasting needed. Wear loose clothing.',
    duration: '15-20 mins',
    reportDelivery: 'Immediate (within 30 mins)',
    popular: true
  },
  {
    id: 'scan-echo-foetal',
    name: 'Foetal ECHO',
    category: 'scan',
    subCategory: 'ECHO (Cardiac Sonography)',
    price: 5500,
    discountPrice: 3000,
    description: 'Specialized ultrasound examination of fetal heart structures, cardiac chambers, valves, and congenital anomaly screening.',
    preparation: 'No fasting required.',
    duration: '30 mins',
    reportDelivery: 'Immediate (within 1 hour)',
    popular: true
  },

  // --- USG GUIDED PROCEDURES ---
  {
    id: 'scan-procedure-fnac',
    name: 'USG Guided FNAC',
    category: 'scan',
    subCategory: 'Interventional Sonography',
    price: 5500,
    discountPrice: 3000,
    description: 'Ultrasound-guided fine needle aspiration cytology procedure for precise diagnostic cell sampling of thyroid, breast, or neck lesions.',
    preparation: 'Prior doctor prescription & coagulation report (PT/INR) required.',
    duration: '20-30 mins',
    reportDelivery: '24-48 Hours'
  },
  {
    id: 'scan-procedure-biopsy',
    name: 'USG Guided Biopsy',
    category: 'scan',
    subCategory: 'Interventional Sonography',
    price: 10000,
    discountPrice: 6000,
    description: 'Real-time ultrasound-guided tissue core needle biopsy procedure performed by expert Radiologist.',
    preparation: 'Fasting 4 hours, doctor referral note, PT-INR & CBC reports mandatory.',
    duration: '30-45 mins',
    reportDelivery: '48-72 Hours'
  },
  // --- LAB / BLOOD TESTS & OFFICIAL ASSURX PATHOLOGY CATALOG ---
  {
    id: 'lab-cbc',
    name: 'Complete Blood Count (CBC) with ESR',
    category: 'lab',
    subCategory: 'General Blood Tests',
    price: 500,
    discountPrice: 290,
    description: 'Vital screening measuring RBC, WBC, Platelets, Hemoglobin, and ESR.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: 'Same Day (within 6 hours)',
    parametersCount: 24,
    popular: true
  },
  {
    id: 'lab-thyroid',
    name: 'Thyroid Profile (T3, T4, Ultra-TSH)',
    category: 'lab',
    subCategory: 'Hormone Assays',
    price: 800,
    discountPrice: 390,
    description: 'Measures key thyroid hormones to evaluate thyroid gland activity.',
    preparation: 'Fasting preferred.',
    duration: '10 mins',
    reportDelivery: 'Same Day',
    parametersCount: 3,
    popular: true
  },
  {
    id: 'lab-diabetes',
    name: 'Diabetes Screen (HbA1c & Fasting Blood Sugar)',
    category: 'lab',
    subCategory: 'Diabetic Profiles',
    price: 600,
    discountPrice: 299,
    description: 'Combines Blood Sugar Fasting with HbA1c to estimate average glucose.',
    preparation: '8-10 hours fasting required.',
    duration: '10 mins',
    reportDelivery: 'Same Day',
    parametersCount: 2,
    popular: true
  },
  {
    id: 'lab-lipid',
    name: 'Lipid Profile (Cholesterol & Triglycerides)',
    category: 'lab',
    subCategory: 'Cardiac Markers',
    price: 900,
    discountPrice: 450,
    description: 'Measures Total Cholesterol, HDL, LDL, VLDL, and Triglycerides.',
    preparation: '10-12 hours overnight fasting strictly required.',
    duration: '10 mins',
    reportDelivery: 'Same Day',
    parametersCount: 7
  },
  {
    id: 'lab-liver-lft',
    name: 'Liver Function Test (LFT)',
    category: 'lab',
    subCategory: 'Organ Screeners',
    price: 1100,
    discountPrice: 550,
    description: 'Analyzes Bilirubin, SGOT, SGPT, Alkaline Phosphatase, Albumin, Globulin.',
    preparation: 'Fasting of 8 hours recommended.',
    duration: '10 mins',
    reportDelivery: 'Same Day',
    parametersCount: 11
  },
  {
    id: 'lab-kidney-kft',
    name: 'Kidney Function Test (KFT / RFT)',
    category: 'lab',
    subCategory: 'Organ Screeners',
    price: 1000,
    discountPrice: 490,
    description: 'Measures Blood Urea, Serum Creatinine, Uric Acid, and Electrolytes.',
    preparation: 'Stay hydrated.',
    duration: '10 mins',
    reportDelivery: 'Same Day',
    parametersCount: 8
  },
  {
    id: 'lab-vitamin-d',
    name: 'Vitamin D (25-Hydroxy)',
    category: 'lab',
    subCategory: 'Vitamins & Minerals',
    price: 1500,
    discountPrice: 600,
    description: 'Measures Vitamin D concentration in blood via CLIA method.',
    preparation: 'Fasting not required.',
    duration: '10 mins',
    reportDelivery: '6 Hours',
    parametersCount: 1,
    popular: true
  },
  {
    id: 'lab-vitamin-b12',
    name: 'Vitamin B12 (Cobalamin)',
    category: 'lab',
    subCategory: 'Vitamins & Minerals',
    price: 1600,
    discountPrice: 1200,
    description: 'Checks levels of Vitamin B12 via CLIA assay.',
    preparation: 'Fasting preferred.',
    duration: '10 mins',
    reportDelivery: '8 Hours',
    parametersCount: 1
  },
  {
    id: 'lab-urine-routine',
    name: 'Urine Routine & Microscopy (URM)',
    category: 'lab',
    subCategory: 'General Lab Tests',
    price: 250,
    discountPrice: 100,
    description: 'Evaluates physical, chemical, and microscopic properties of urine.',
    preparation: 'Clean morning urine sample.',
    duration: '5 mins',
    reportDelivery: '6 Hours',
    parametersCount: 18,
    popular: true
  },
  {
    id: 'lab-heavy-metals-lead',
    name: 'Lead Level - Blood (A344)',
    category: 'lab',
    subCategory: 'Heavy Metals & Special',
    price: 1600,
    discountPrice: 1200,
    description: 'ICP-MS quantitative heavy metal evaluation for Lead in EDTA blood sample.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '12 Hours'
  },
  {
    id: 'lab-heavy-metals-mercury',
    name: 'Mercury Level - Blood (A344)',
    category: 'lab',
    subCategory: 'Heavy Metals & Special',
    price: 1600,
    discountPrice: 1200,
    description: 'ICP-MS heavy metal assessment for Mercury exposure.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '12 Hours'
  },
  {
    id: 'lab-heavy-metals-zinc',
    name: 'Zinc Level - Blood (A344)',
    category: 'lab',
    subCategory: 'Heavy Metals & Special',
    price: 1600,
    discountPrice: 1200,
    description: 'ICP-MS mineral evaluation of Serum/EDTA Zinc concentration.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '12 Hours'
  },
  {
    id: 'lab-heavy-metals-copper',
    name: 'Copper Level - Blood (A228)',
    category: 'lab',
    subCategory: 'Heavy Metals & Special',
    price: 1600,
    discountPrice: 1200,
    description: 'ICP-MS analysis of Serum/EDTA Copper level.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '12 Hours'
  },
  {
    id: 'lab-dengue-profile',
    name: 'Dengue Profile (NS1, IgG, IgM) (A359)',
    category: 'lab',
    subCategory: 'Infectious Diseases',
    price: 1500,
    discountPrice: 1000,
    description: 'Rapid Card screening for Dengue NS1 Antigen, IgG and IgM Antibodies.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '6 Hours',
    popular: true
  },
  {
    id: 'lab-insulin-serum',
    name: 'Insulin - Fasting / Random (A344)',
    category: 'lab',
    subCategory: 'Hormone Assays',
    price: 1000,
    discountPrice: 600,
    description: 'CLIA quantitative evaluation of Serum Insulin levels.',
    preparation: 'Fasting 8-10 hours required for Fasting Insulin.',
    duration: '10 mins',
    reportDelivery: '12 Hours'
  },
  {
    id: 'lab-electrolytes-sodium',
    name: 'Serum Sodium (A51)',
    category: 'lab',
    subCategory: 'Organ Screeners',
    price: 250,
    discountPrice: 169,
    description: 'Ion Selective Electrode measurement of Serum Sodium.',
    preparation: 'No fasting required.',
    duration: '5 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-electrolytes-potassium',
    name: 'Serum Potassium (A81)',
    category: 'lab',
    subCategory: 'Organ Screeners',
    price: 250,
    discountPrice: 169,
    description: 'Ion Selective Electrode assay for Serum Potassium.',
    preparation: 'No fasting required.',
    duration: '5 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-acth-hormone',
    name: 'ACTH - Adrenocorticotropic Hormone (A89)',
    category: 'lab',
    subCategory: 'Hormone Assays',
    price: 1500,
    discountPrice: 1100,
    description: 'CLIA assessment of pituitary ACTH hormone concentration.',
    preparation: 'Morning blood sample preferred.',
    duration: '10 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-amh-hormone',
    name: 'AMH - Anti-Mullerian Hormone (A82)',
    category: 'lab',
    subCategory: 'Hormone Assays',
    price: 2500,
    discountPrice: 1800,
    description: 'CLIA quantitative evaluation of ovarian reserve and fertility potential.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '12 Hours',
    popular: true
  },
  {
    id: 'lab-ana-autoantibody',
    name: 'ANA - Anti-Nuclear Antibody (A220)',
    category: 'lab',
    subCategory: 'Allergy & Autoimmune',
    price: 1000,
    discountPrice: 700,
    description: 'CLIA autoimmune antibody screening for Lupus, RA, and connective tissue disorders.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '12 Hours'
  },
  {
    id: 'lab-anti-tpo',
    name: 'Anti-TPO Thyroid Antibodies (A68)',
    category: 'lab',
    subCategory: 'Hormone Assays',
    price: 1750,
    discountPrice: 1100,
    description: 'CLIA evaluation for Hashimoto thyroiditis and autoimmune thyroid diseases.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '12 Hours'
  },
  {
    id: 'lab-anti-ccp',
    name: 'Anti-CCP Antibody (A222)',
    category: 'lab',
    subCategory: 'Allergy & Autoimmune',
    price: 1700,
    discountPrice: 1200,
    description: 'CLIA specific marker for early and aggressive Rheumatoid Arthritis.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-allergy-full-panel',
    name: 'Allergy Full Panel (Food + Inhalant + Drug + Non-Veg) (A255)',
    category: 'lab',
    subCategory: 'Allergy & Autoimmune',
    price: 20000,
    discountPrice: 10000,
    description: 'Comprehensive 100+ allergen screening covering food, dust, pollen, drugs, and non-veg proteins.',
    preparation: 'No fasting required.',
    duration: '15 mins',
    reportDelivery: '72 Hours',
    popular: true
  },
  {
    id: 'lab-allergy-food-panel',
    name: 'Allergy Panel - Food (A250)',
    category: 'lab',
    subCategory: 'Allergy & Autoimmune',
    price: 9000,
    discountPrice: 3800,
    description: 'Serum allergy screening for common food allergens, gluten, dairy, nuts, and spices.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '72 Hours'
  },
  {
    id: 'lab-afp-tumor-marker',
    name: 'Alpha-Fetoprotein (AFP) Tumor Marker (A99)',
    category: 'lab',
    subCategory: 'Tumor Markers',
    price: 1200,
    discountPrice: 800,
    description: 'CLIA tumor marker screening for liver, germ cell, and testicular neoplasms.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '8 Hours'
  },
  {
    id: 'lab-ca-125',
    name: 'CA 125 Ovarian Tumor Marker (A95)',
    category: 'lab',
    subCategory: 'Tumor Markers',
    price: 1000,
    discountPrice: 750,
    description: 'CLIA diagnostic marker for ovarian cancer screening and monitoring.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '12 Hours'
  },
  {
    id: 'lab-ca-19-9',
    name: 'CA 19-9 Pancreatic & GI Marker (A96)',
    category: 'lab',
    subCategory: 'Tumor Markers',
    price: 1000,
    discountPrice: 750,
    description: 'CLIA screening for pancreatic, gallbladder, and gastrointestinal cancers.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '12 Hours'
  },
  {
    id: 'lab-cea-marker',
    name: 'CEA - Carcinoembryonic Antigen (A98)',
    category: 'lab',
    subCategory: 'Tumor Markers',
    price: 1200,
    discountPrice: 800,
    description: 'CLIA broad-spectrum tumor marker for colorectal and GI tract cancers.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '12 Hours'
  },
  {
    id: 'lab-beta-hcg',
    name: 'Beta-hCG Total Quantitative (A92)',
    category: 'lab',
    subCategory: 'Hormone Assays',
    price: 1000,
    discountPrice: 800,
    description: 'CLIA pregnancy confirmation and gestational age measurement.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '12 Hours',
    popular: true
  },
  {
    id: 'lab-double-marker-fmf',
    name: 'Double Marker 1st Trimester (FMF Certified) (A420)',
    category: 'lab',
    subCategory: 'Hormone Assays',
    price: 4000,
    discountPrice: 2500,
    description: 'FMF certified 8-13 week maternal screening for Down syndrome risk assessment.',
    preparation: 'Ultrasound NT scan report required.',
    duration: '10 mins',
    reportDelivery: '48 Hours'
  },
  {
    id: 'lab-esr-westergren',
    name: 'ESR - Erythrocyte Sedimentation Rate (A06)',
    category: 'lab',
    subCategory: 'General Blood Tests',
    price: 200,
    discountPrice: 100,
    description: 'Modified Westergren method evaluating systemic inflammation and infection.',
    preparation: 'No fasting required.',
    duration: '5 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-ferritin-serum',
    name: 'Serum Ferritin (A35)',
    category: 'lab',
    subCategory: 'General Blood Tests',
    price: 1000,
    discountPrice: 650,
    description: 'CLIA iron storage level measurement for anemia or iron overload evaluation.',
    preparation: 'Fasting preferred.',
    duration: '10 mins',
    reportDelivery: '12 Hours'
  },
  {
    id: 'lab-folic-acid',
    name: 'Folate / Vitamin B9 (A93)',
    category: 'lab',
    subCategory: 'Vitamins & Minerals',
    price: 1300,
    discountPrice: 1000,
    description: 'CLIA assessment of Serum Folate concentration for megaloblastic anemia.',
    preparation: '8 hours fasting preferred.',
    duration: '10 mins',
    reportDelivery: '8 Hours'
  },
  {
    id: 'lab-fsh-lh-prl',
    name: 'FSH - Follicle Stimulating Hormone (A76)',
    category: 'lab',
    subCategory: 'Hormone Assays',
    price: 600,
    discountPrice: 400,
    description: 'CLIA evaluation of pituitary FSH for fertility, PCOS, and menstrual cycle.',
    preparation: 'Day 2-5 of menstrual cycle preferred.',
    duration: '10 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-lh-hormone',
    name: 'LH - Luteinizing Hormone (A121)',
    category: 'lab',
    subCategory: 'Hormone Assays',
    price: 600,
    discountPrice: 350,
    description: 'CLIA measurement of LH for ovulation timing and reproductive hormone health.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-prolactin',
    name: 'Prolactin (A169)',
    category: 'lab',
    subCategory: 'Hormone Assays',
    price: 1000,
    discountPrice: 500,
    description: 'CLIA evaluation of pituitary Prolactin level for hyperprolactinemia.',
    preparation: 'Morning sample 2 hours after waking up.',
    duration: '10 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-progesterone',
    name: 'Progesterone (A37)',
    category: 'lab',
    subCategory: 'Hormone Assays',
    price: 1000,
    discountPrice: 600,
    description: 'CLIA luteal phase progesterone measurement for ovulation check.',
    preparation: 'Day 21 of menstrual cycle preferred.',
    duration: '10 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-testosterone-total',
    name: 'Testosterone Total (A63)',
    category: 'lab',
    subCategory: 'Hormone Assays',
    price: 1000,
    discountPrice: 600,
    description: 'Measurement of total testosterone for androgenic health.',
    preparation: 'Morning fasting blood sample.',
    duration: '10 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-psa-prostate',
    name: 'PSA - Prostate Specific Antigen (A71)',
    category: 'lab',
    subCategory: 'Tumor Markers',
    price: 1000,
    discountPrice: 550,
    description: 'CLIA screening for prostate health and prostate cancer risk in men.',
    preparation: 'Avoid heavy exercise 24 hours prior.',
    duration: '10 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-pt-inr',
    name: 'PT / INR Prothrombin Time (A422)',
    category: 'lab',
    subCategory: 'General Blood Tests',
    price: 400,
    discountPrice: 250,
    description: 'Photo optical clot detection measuring blood coagulation time and INR.',
    preparation: 'No special fasting required.',
    duration: '10 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-ra-factor',
    name: 'Rheumatoid Factor (RF Quantitative) (A126)',
    category: 'lab',
    subCategory: 'Allergy & Autoimmune',
    price: 600,
    discountPrice: 450,
    description: 'Immunoturbidimetry quantitative test for Rheumatoid Arthritis.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-torch-panel-8',
    name: 'TORCH Panel (All 8 Tests) (A55)',
    category: 'lab',
    subCategory: 'Infectious Diseases',
    price: 3500,
    discountPrice: 2500,
    description: 'Complete IgG & IgM antibody screening for Toxoplasma, Rubella, CMV, and HSV 1&2 in pregnancy.',
    preparation: 'No fasting required.',
    duration: '15 mins',
    reportDelivery: '18 Hours',
    popular: true
  },
  {
    id: 'lab-widal-typhoid',
    name: 'Widal Test for Typhoid (A430)',
    category: 'lab',
    subCategory: 'Infectious Diseases',
    price: 300,
    discountPrice: 200,
    description: 'Slide & tube agglutination screening for Salmonella Typhi antibodies.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-super-healthy-diamond',
    name: 'Super Healthy Profile Diamond (122 Tests) (A166)',
    category: 'lab',
    subCategory: 'Organ Screeners',
    price: 4000,
    discountPrice: 2000,
    description: 'Full body master health checkup covering 122 bio-markers including CBC, LFT, KFT, Lipid, Thyroid, HbA1c, Electrolytes, Vitamins.',
    preparation: '10-12 hours fasting mandatory.',
    duration: '15 mins',
    reportDelivery: '18 Hours',
    popular: true
  },
  {
    id: 'lab-super-healthy-gold',
    name: 'Super Healthy Profile Gold (47 Tests) (A151)',
    category: 'lab',
    subCategory: 'Organ Screeners',
    price: 2000,
    discountPrice: 1200,
    description: 'Essential full body health package with 47 parameters.',
    preparation: '10-12 hours fasting mandatory.',
    duration: '15 mins',
    reportDelivery: '18 Hours'
  },
  {
    id: 'lab-sports-fitness-advanced',
    name: 'Sports Fitness Advanced (143 Tests) (A242)',
    category: 'lab',
    subCategory: 'Organ Screeners',
    price: 10000,
    discountPrice: 7000,
    description: 'Ultra comprehensive athletic, cardiac, metabolic, and muscle recovery profile.',
    preparation: '10-12 hours fasting mandatory.',
    duration: '15 mins',
    reportDelivery: '24 Hours'
  },
  {
    id: 'lab-ada-ascitic-fluid',
    name: 'Adenosine Deaminase (ADA) - Ascitic Fluid (A258)',
    category: 'lab',
    subCategory: 'Heavy Metals & Special',
    price: 950,
    discountPrice: 500,
    description: 'Photometry assay of ADA in Ascitic Fluid to screen abdominal tuberculosis.',
    preparation: 'Doctor referral required.',
    duration: '10 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-ada-csf',
    name: 'Adenosine Deaminase (ADA) - CSF (A264)',
    category: 'lab',
    subCategory: 'Heavy Metals & Special',
    price: 950,
    discountPrice: 500,
    description: 'Photometry measurement of ADA level in Cerebrospinal Fluid (CSF).',
    preparation: 'Clinical procedure required.',
    duration: '10 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-ada-pleural',
    name: 'Adenosine Deaminase (ADA) - Pleural Fluid (A262)',
    category: 'lab',
    subCategory: 'Heavy Metals & Special',
    price: 950,
    discountPrice: 500,
    description: 'Photometry assessment of Pleural Fluid ADA for tubercular pleurisy.',
    preparation: 'Clinical sample required.',
    duration: '10 mins',
    reportDelivery: '8 Hours'
  },
  {
    id: 'lab-ada-synovial',
    name: 'Adenosine Deaminase (ADA) - Synovial Fluid (A263)',
    category: 'lab',
    subCategory: 'Heavy Metals & Special',
    price: 950,
    discountPrice: 500,
    description: 'Photometry evaluation of Synovial Fluid ADA.',
    preparation: 'Clinical sample required.',
    duration: '10 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-acetylcholine-receptor',
    name: 'Acetylcholine Receptor Autoantibody (A189)',
    category: 'lab',
    subCategory: 'Allergy & Autoimmune',
    price: 4000,
    discountPrice: 2800,
    description: 'Non-Isotopic Assay for Myasthenia Gravis diagnosis.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '72 Hours'
  },
  {
    id: 'lab-afb-smear-zn',
    name: 'AFB Smear (Z-N Stain) (A259)',
    category: 'lab',
    subCategory: 'Infectious Diseases',
    price: 500,
    discountPrice: 300,
    description: 'Microscopic Ziehl-Neelsen stain evaluation for Acid-Fast Bacilli (TB).',
    preparation: 'Early morning deep cough sputum sample.',
    duration: '10 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-sgpt-alt',
    name: 'Alanine Transaminase (SGPT / ALT) (A41)',
    category: 'lab',
    subCategory: 'Organ Screeners',
    price: 200,
    discountPrice: 149,
    description: 'Photometry measurement of SGPT liver enzyme activity.',
    preparation: 'Fasting preferred.',
    duration: '5 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-sgot-ast',
    name: 'Aspartate Aminotransferase (SGOT / AST) (A40)',
    category: 'lab',
    subCategory: 'Organ Screeners',
    price: 200,
    discountPrice: 150,
    description: 'Photometry evaluation of SGOT cardiac and hepatic tissue enzyme.',
    preparation: 'Fasting preferred.',
    duration: '5 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-albumin-serum',
    name: 'Albumin - Serum (A44)',
    category: 'lab',
    subCategory: 'Organ Screeners',
    price: 200,
    discountPrice: 150,
    description: 'BCG method quantitative analysis of Serum Albumin level.',
    preparation: 'No fasting required.',
    duration: '5 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-alkaline-phosphatase',
    name: 'Alkaline Phosphatase (ALP) (A42)',
    category: 'lab',
    subCategory: 'Organ Screeners',
    price: 200,
    discountPrice: 150,
    description: 'Modified IFCC method measuring ALP enzyme for liver and bone health.',
    preparation: 'Fasting preferred.',
    duration: '5 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-allergy-drug',
    name: 'Allergy Panel - Drug (A249)',
    category: 'lab',
    subCategory: 'Allergy & Autoimmune',
    price: 9000,
    discountPrice: 3500,
    description: 'Serum allergy screening for common pharmaceutical and antibiotic sensitivities.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '72 Hours'
  },
  {
    id: 'lab-allergy-inhalant',
    name: 'Allergy Panel - Inhalant (A251)',
    category: 'lab',
    subCategory: 'Allergy & Autoimmune',
    price: 8000,
    discountPrice: 3200,
    description: 'Serum allergy panel testing airborne dust mites, pollens, fungi, and pet dander.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '72 Hours'
  },
  {
    id: 'lab-allergy-nonveg',
    name: 'Allergy Panel - Non Veg (A254)',
    category: 'lab',
    subCategory: 'Allergy & Autoimmune',
    price: 7000,
    discountPrice: 2900,
    description: 'Serum allergy panel testing egg, fish, chicken, mutton, and seafood proteins.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '72 Hours'
  },
  {
    id: 'lab-amino-acid-profile',
    name: 'Amino Acid Profile (35 Parameters) (A373)',
    category: 'lab',
    subCategory: 'Heavy Metals & Special',
    price: 3000,
    discountPrice: 2000,
    description: 'LC-MS/MS advanced screening for inborn errors of metabolism and amino acid disorders.',
    preparation: '10-12 hours fasting required.',
    duration: '15 mins',
    reportDelivery: '24 Hours'
  },
  {
    id: 'lab-amylase-serum',
    name: 'Amylase - Serum (A393)',
    category: 'lab',
    subCategory: 'Organ Screeners',
    price: 500,
    discountPrice: 350,
    description: 'Enzymatic Colorimetric Test measuring pancreatic Amylase enzyme in blood.',
    preparation: 'Fasting of 8 hours recommended.',
    duration: '5 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-anemia-profile-basic',
    name: 'Anemia Profile - Basic (69 Tests) (A374)',
    category: 'lab',
    subCategory: 'General Blood Tests',
    price: 3500,
    discountPrice: 2500,
    description: 'Comprehensive screening for iron deficiency, megaloblastic, and hemolytic anemia.',
    preparation: 'Overnight fasting required.',
    duration: '10 mins',
    reportDelivery: '12 Hours',
    popular: true
  },
  {
    id: 'lab-anemia-profile-advanced',
    name: 'Anemia Profile - Advanced (102 Tests) (A383)',
    category: 'lab',
    subCategory: 'General Blood Tests',
    price: 6000,
    discountPrice: 4500,
    description: 'Master anemia diagnostic panel covering 102 biomarkers including hemoglobin variants and iron studies.',
    preparation: 'Overnight fasting required.',
    duration: '15 mins',
    reportDelivery: '12 Hours'
  },
  {
    id: 'lab-anti-chlamydia-igg',
    name: 'Anti Chlamydia Antibody IgG (A115)',
    category: 'lab',
    subCategory: 'Infectious Diseases',
    price: 800,
    discountPrice: 400,
    description: 'ELISA screening for Chlamydia trachomatis past or chronic infection.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '32 Hours'
  },
  {
    id: 'lab-anti-chlamydia-igm',
    name: 'Anti Chlamydia Antibody IgM (A152)',
    category: 'lab',
    subCategory: 'Infectious Diseases',
    price: 800,
    discountPrice: 400,
    description: 'ELISA detection of active acute Chlamydia infection antibodies.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '32 Hours'
  },
  {
    id: 'lab-anti-dsdna',
    name: 'Anti-dsDNA Antibody (A269)',
    category: 'lab',
    subCategory: 'Allergy & Autoimmune',
    price: 1200,
    discountPrice: 800,
    description: 'ELISA specific confirmatory biomarker for Systemic Lupus Erythematosus (SLE).',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '24 Hours'
  },
  {
    id: 'lab-apolipoprotein-a1-b',
    name: 'Apolipoprotein A1 & B (A102/A104)',
    category: 'lab',
    subCategory: 'Cardiac Markers',
    price: 1560,
    discountPrice: 1200,
    description: 'Immunoturbidimetry ratio measurement evaluating atherogenic risk and heart disease profile.',
    preparation: '10-12 hours fasting required.',
    duration: '10 mins',
    reportDelivery: '12 Hours'
  },
  {
    id: 'lab-arthritis-profile-basic',
    name: 'Arthritis Profile - Basic (A388)',
    category: 'lab',
    subCategory: 'Allergy & Autoimmune',
    price: 5000,
    discountPrice: 2800,
    description: 'Joint pain diagnostic profile including RA Factor, Uric Acid, CRP, ESR, and CBC.',
    preparation: 'Fasting preferred.',
    duration: '10 mins',
    reportDelivery: '24 Hours'
  },
  {
    id: 'lab-arthritis-profile-advanced',
    name: 'Arthritis Profile - Advanced (A389)',
    category: 'lab',
    subCategory: 'Allergy & Autoimmune',
    price: 6000,
    discountPrice: 4200,
    description: 'Master joint inflammation panel covering Anti-CCP, ANA, RA Factor, CRP, Uric Acid, Calcium, and Phosphorus.',
    preparation: 'Fasting preferred.',
    duration: '15 mins',
    reportDelivery: '24 Hours'
  },
  {
    id: 'lab-beta-2-microglobulin',
    name: 'Beta-2 Microglobulin (A100)',
    category: 'lab',
    subCategory: 'Tumor Markers',
    price: 1200,
    discountPrice: 800,
    description: 'ELISA tumor marker evaluating multiple myeloma, lymphoma, and renal tubular function.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '12 Hours'
  },
  {
    id: 'lab-blood-glucose-fasting',
    name: 'Blood Glucose - Fasting (A26)',
    category: 'lab',
    subCategory: 'Diabetic Profiles',
    price: 150,
    discountPrice: 50,
    description: 'GOD-POD enzymatic plasma glucose estimation after 8-10 hours fasting.',
    preparation: 'Strict 8-10 hours overnight fasting required.',
    duration: '5 mins',
    reportDelivery: '3 Hours',
    popular: true
  },
  {
    id: 'lab-blood-glucose-pp',
    name: 'Blood Glucose - Postprandial (PP) (A27)',
    category: 'lab',
    subCategory: 'Diabetic Profiles',
    price: 150,
    discountPrice: 50,
    description: 'GOD-POD enzymatic plasma glucose estimation exactly 2 hours post meal.',
    preparation: 'Blood sample 2 hours after breakfast/meal.',
    duration: '5 mins',
    reportDelivery: '3 Hours'
  },
  {
    id: 'lab-rbs-glucose',
    name: 'Random Blood Glucose (RBS) (A23)',
    category: 'lab',
    subCategory: 'Diabetic Profiles',
    price: 150,
    discountPrice: 50,
    description: 'GOD-POD enzymatic instant random blood sugar test.',
    preparation: 'No fasting required.',
    duration: '5 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-blood-grouping',
    name: 'Blood Grouping & Rh Typing (A192)',
    category: 'lab',
    subCategory: 'General Blood Tests',
    price: 200,
    discountPrice: 100,
    description: 'Agglutination method determination of ABO blood group and Rh factor D positivity.',
    preparation: 'No fasting required.',
    duration: '5 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-bun-blood-urea',
    name: 'Blood Urea Nitrogen (BUN) (A47)',
    category: 'lab',
    subCategory: 'Organ Screeners',
    price: 200,
    discountPrice: 150,
    description: 'Calculated BUN assay evaluating renal clearance and protein breakdown.',
    preparation: 'Stay hydrated.',
    duration: '5 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-calcium-serum',
    name: 'Calcium - Serum (A30)',
    category: 'lab',
    subCategory: 'Vitamins & Minerals',
    price: 250,
    discountPrice: 150,
    description: 'Photometry quantitative measurement of total serum Calcium.',
    preparation: 'Fasting preferred.',
    duration: '5 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-calcitonin',
    name: 'Calcitonin (A74)',
    category: 'lab',
    subCategory: 'Tumor Markers',
    price: 1000,
    discountPrice: 650,
    description: 'CLIA thyroid C-cell tumor marker for medullary thyroid carcinoma.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '12 Hours'
  },
  {
    id: 'lab-chikungunya-ab',
    name: 'Chikungunya IgM/IgG Antibody (A127)',
    category: 'lab',
    subCategory: 'Infectious Diseases',
    price: 1200,
    discountPrice: 600,
    description: 'Immunoassay screening for acute or previous Chikungunya viral fever.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '12 Hours'
  },
  {
    id: 'lab-cpk-ck-total',
    name: 'Creatine Phosphokinase (CK / CPK Total) (A39)',
    category: 'lab',
    subCategory: 'Cardiac Markers',
    price: 500,
    discountPrice: 300,
    description: 'DGKC method enzyme marker for muscle dystrophy, injury, or cardiac strain.',
    preparation: 'Avoid strenuous physical activity prior to test.',
    duration: '5 mins',
    reportDelivery: '12 Hours'
  },
  {
    id: 'lab-ck-mb-cardiac',
    name: 'CK-MB Cardiac Isoenzyme (A116)',
    category: 'lab',
    subCategory: 'Cardiac Markers',
    price: 1200,
    discountPrice: 700,
    description: 'CLIA specific cardiac biomarker for myocardial ischemia evaluation.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-d-dimer-coagulation',
    name: 'D-Dimer (A38)',
    category: 'lab',
    subCategory: 'Cardiac Markers',
    price: 1500,
    discountPrice: 1000,
    description: 'CLIA fibrin degradation fragment assay to rule out DVT, pulmonary embolism, or DIC.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-dheas-adrenal',
    name: 'Dehydroepiandrosterone Sulfate (DHEAS) (A83)',
    category: 'lab',
    subCategory: 'Hormone Assays',
    price: 2000,
    discountPrice: 1200,
    description: 'CLIA adrenal androgen evaluation for hirsutism, PCOS, and adrenal tumors.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '12 Hours'
  },
  {
    id: 'lab-diabetic-profile-platinum',
    name: 'Diabetic Profile - Platinum (48 Tests) (A376)',
    category: 'lab',
    subCategory: 'Diabetic Profiles',
    price: 2000,
    discountPrice: 1200,
    description: 'Master diabetes monitoring panel including HbA1c, Fasting & PP Glucose, Lipid Profile, KFT, and Urine Microalbumin.',
    preparation: '10 hours overnight fasting required.',
    duration: '15 mins',
    reportDelivery: '12 Hours'
  },
  {
    id: 'lab-diabetic-profile-diamond',
    name: 'Diabetic Profile - Diamond (52 Tests) (A377)',
    category: 'lab',
    subCategory: 'Diabetic Profiles',
    price: 3000,
    discountPrice: 2000,
    description: 'Advanced diabetic organ complication screener with 52 bio-markers.',
    preparation: '10 hours overnight fasting required.',
    duration: '15 mins',
    reportDelivery: '12 Hours'
  },
  {
    id: 'lab-hba1c-hplc',
    name: 'HbA1c (HPLC Method with Graph) (A204)',
    category: 'lab',
    subCategory: 'Diabetic Profiles',
    price: 750,
    discountPrice: 450,
    description: 'Gold-standard NGSP-certified HPLC method for 3-month average blood glucose.',
    preparation: 'No fasting required.',
    duration: '5 mins',
    reportDelivery: '6 Hours',
    popular: true
  },
  {
    id: 'lab-hbsag-hepatitis-b',
    name: 'HBsAg (Hepatitis B Surface Antigen) (A182)',
    category: 'lab',
    subCategory: 'Infectious Diseases',
    price: 800,
    discountPrice: 500,
    description: 'CLIA diagnostic screening for active Hepatitis B viral infection.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-hcv-hepatitis-c',
    name: 'Hepatitis C Virus (HCV Antibody) (A113)',
    category: 'lab',
    subCategory: 'Infectious Diseases',
    price: 800,
    discountPrice: 500,
    description: 'CLIA diagnostic screening for Hepatitis C antibodies.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-hiv-western-blot',
    name: 'HIV - Western Blot Confirmatory (A94)',
    category: 'lab',
    subCategory: 'Infectious Diseases',
    price: 5000,
    discountPrice: 3000,
    description: 'Paper Chromatography confirmatory test for HIV 1 & 2 infection.',
    preparation: 'Doctor referral required.',
    duration: '15 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-hla-b27-pcr',
    name: 'HLA B27 Qualitative PCR (A103)',
    category: 'lab',
    subCategory: 'Allergy & Autoimmune',
    price: 5000,
    discountPrice: 2400,
    description: 'Real-time PCR genetic assay for Ankylosing Spondylitis and autoimmune arthritis.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '80 Hours'
  },
  {
    id: 'lab-homocysteine',
    name: 'Homocysteine (A212)',
    category: 'lab',
    subCategory: 'Cardiac Markers',
    price: 1500,
    discountPrice: 1000,
    description: 'Photometry assay evaluating vascular stroke, thrombosis, and cardiac risk.',
    preparation: '10 hours fasting required.',
    duration: '10 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-hs-crp',
    name: 'hs-CRP (High Sensitivity C-Reactive Protein) (A210)',
    category: 'lab',
    subCategory: 'Cardiac Markers',
    price: 700,
    discountPrice: 500,
    description: 'CLIA high-sensitivity marker for cardiac vascular inflammation.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-pth-parathyroid',
    name: 'INTACT Parathyroid Hormone (PTH) (A34)',
    category: 'lab',
    subCategory: 'Hormone Assays',
    price: 1600,
    discountPrice: 1200,
    description: 'CLIA assessment of PTH for calcium metabolism and parathyroid disease.',
    preparation: 'Morning blood sample preferred.',
    duration: '10 mins',
    reportDelivery: '12 Hours'
  },
  {
    id: 'lab-iron-deficiency-profile',
    name: 'Iron Deficiency Profile (Serum Iron, TIBC, Ferritin) (A418)',
    category: 'lab',
    subCategory: 'General Blood Tests',
    price: 800,
    discountPrice: 600,
    description: 'Complete iron panel measuring Serum Iron, TIBC, UIBC, and Ferritin.',
    preparation: 'Fasting preferred.',
    duration: '10 mins',
    reportDelivery: '12 Hours'
  },
  {
    id: 'lab-kidney-profile-full',
    name: 'Kidney Profile Full (14 Tests) (A312)',
    category: 'lab',
    subCategory: 'Organ Screeners',
    price: 2000,
    discountPrice: 1400,
    description: 'Comprehensive renal evaluation measuring Urea, Creatinine, Uric Acid, BUN, Sodium, Potassium, Chloride, Calcium, and Phosphorus.',
    preparation: 'Stay hydrated.',
    duration: '10 mins',
    reportDelivery: '8 Hours'
  },
  {
    id: 'lab-ldh-total',
    name: 'Lactate Dehydrogenase (LDH) (A57)',
    category: 'lab',
    subCategory: 'Organ Screeners',
    price: 500,
    discountPrice: 300,
    description: 'Photometry measurement of tissue LDH enzyme for tissue breakdown monitoring.',
    preparation: 'No fasting required.',
    duration: '5 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-lipid-profile-full',
    name: 'Lipid Profile Full (A174)',
    category: 'lab',
    subCategory: 'Cardiac Markers',
    price: 700,
    discountPrice: 500,
    description: 'Complete lipid profile evaluating Cholesterol, HDL, LDL, VLDL, Triglycerides, and Risk Ratios.',
    preparation: '12 hours overnight fasting strictly required.',
    duration: '10 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-lft-liver-full',
    name: 'Liver Function Test (LFT Full) (A199)',
    category: 'lab',
    subCategory: 'Organ Screeners',
    price: 950,
    discountPrice: 450,
    description: 'Complete liver panel measuring Bilirubin Total/Direct/Indirect, SGOT, SGPT, ALP, Total Protein, Albumin, and Globulin.',
    preparation: 'Fasting 8 hours recommended.',
    duration: '10 mins',
    reportDelivery: '6 Hours',
    popular: true
  },
  {
    id: 'lab-magnesium-serum',
    name: 'Magnesium - Serum (A49)',
    category: 'lab',
    subCategory: 'Vitamins & Minerals',
    price: 750,
    discountPrice: 500,
    description: 'Photometry quantitative measurement of Serum Magnesium.',
    preparation: 'No fasting required.',
    duration: '5 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-malaria-antigen-mpda',
    name: 'Malaria Antigen Detection (Rapid Card / MPDA) (A389)',
    category: 'lab',
    subCategory: 'Infectious Diseases',
    price: 550,
    discountPrice: 450,
    description: 'Rapid immunochromatographic card detection for P. falciparum and P. vivax.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '6 Hours',
    popular: true
  },
  {
    id: 'lab-mantoux-test',
    name: 'Mantoux Test (Tuberculin Skin Test) (A09)',
    category: 'lab',
    subCategory: 'Infectious Diseases',
    price: 500,
    discountPrice: 250,
    description: 'Intradermal tuberculin injection with reading after 48-72 hours for TB exposure.',
    preparation: 'Requires in-center visit for injection & 48-72h reading.',
    duration: '15 mins',
    reportDelivery: '48-72 Hours'
  },
  {
    id: 'lab-measles-igg-igm',
    name: 'Measles IgG / IgM Antibody (A424/A425)',
    category: 'lab',
    subCategory: 'Infectious Diseases',
    price: 1000,
    discountPrice: 650,
    description: 'ELISA screening for Rubeola (Measles) viral immunity and active infection.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-mumps-igg-igm',
    name: 'Mumps IgG / IgM Antibody (A118/A172)',
    category: 'lab',
    subCategory: 'Infectious Diseases',
    price: 1000,
    discountPrice: 800,
    description: 'ELISA screening for Mumps viral antibodies.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '8 Hours'
  },
  {
    id: 'lab-occult-blood-urine',
    name: 'Occult Blood Test - Urine (A385)',
    category: 'lab',
    subCategory: 'General Lab Tests',
    price: 500,
    discountPrice: 200,
    description: 'Rapid assay screening for microscopic hematuria in urine.',
    preparation: 'Fresh morning urine sample.',
    duration: '5 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-pap-smear',
    name: 'PAP Smear (Cervical Cytology) (A07)',
    category: 'lab',
    subCategory: 'Heavy Metals & Special',
    price: 1000,
    discountPrice: 600,
    description: 'Microscopic cervical smear screening for precancerous lesions and dysplastic cells.',
    preparation: 'Avoid douching 48 hours prior.',
    duration: '15 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-phosphorus-serum',
    name: 'Phosphorus - Serum (A164)',
    category: 'lab',
    subCategory: 'Vitamins & Minerals',
    price: 250,
    discountPrice: 200,
    description: 'Photometry quantitative analysis of Serum Inorganic Phosphorus.',
    preparation: 'Fasting preferred.',
    duration: '5 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-progesterone-serum',
    name: 'Progesterone (A37)',
    category: 'lab',
    subCategory: 'Hormone Assays',
    price: 1000,
    discountPrice: 600,
    description: 'CLIA luteal phase progesterone assay evaluating ovulation status.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-quadruple-marker',
    name: 'Quadruple Marker 2nd Trimester (14-22 Weeks) (A12)',
    category: 'lab',
    subCategory: 'Hormone Assays',
    price: 4500,
    discountPrice: 3250,
    description: 'Maternal serum screening measuring AFP, hCG, uE3, and Inhibin-A for fetal neural tube and chromosomal risk.',
    preparation: 'Ultrasound gestational age report required.',
    duration: '10 mins',
    reportDelivery: '48 Hours'
  },
  {
    id: 'lab-rubella-igg-igm',
    name: 'Rubella IgG / IgM Antibody (A280/A133)',
    category: 'lab',
    subCategory: 'Infectious Diseases',
    price: 600,
    discountPrice: 320,
    description: 'ELISA screening for German Measles (Rubella) immunity in antenatal care.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-semen-analysis',
    name: 'Semen Analysis (A344)',
    category: 'lab',
    subCategory: 'Heavy Metals & Special',
    price: 1000,
    discountPrice: 700,
    description: 'Microscopic evaluation of sperm count, motility, morphology, and liquefaction time.',
    preparation: 'Abstinence of 3-5 days strictly required.',
    duration: '20 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-shbg-hormone',
    name: 'Sex Hormone Binding Globulin (SHBG) (A398)',
    category: 'lab',
    subCategory: 'Hormone Assays',
    price: 1500,
    discountPrice: 1000,
    description: 'CLIA measurement of SHBG binding protein for free testosterone calculation.',
    preparation: 'Morning blood sample.',
    duration: '10 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-smokers-panel-basic',
    name: 'Smokers Panel - Basic (A415)',
    category: 'lab',
    subCategory: 'Organ Screeners',
    price: 3500,
    discountPrice: 2500,
    description: 'Targeted health screening for smokers evaluating CBC, Lipid, Carboxyhemoglobin, and Vitamin C/D.',
    preparation: '10 hours fasting required.',
    duration: '15 mins',
    reportDelivery: '12 Hours'
  },
  {
    id: 'lab-sports-fitness-gold',
    name: 'Sports Fitness - Gold (92 Tests) (A156)',
    category: 'lab',
    subCategory: 'Organ Screeners',
    price: 2700,
    discountPrice: 2000,
    description: 'Comprehensive athlete fitness panel covering metabolic, muscle, liver, renal, and vitamin profiles.',
    preparation: '10 hours fasting required.',
    duration: '15 mins',
    reportDelivery: '12 Hours'
  },
  {
    id: 'lab-tb-gold-igra',
    name: 'TB Gold (QuantiFERON IGRA) (A107)',
    category: 'lab',
    subCategory: 'Infectious Diseases',
    price: 4500,
    discountPrice: 4000,
    description: 'Interferon Gamma Release Assay (IGRA) blood test for latent Mycobacterium tuberculosis.',
    preparation: 'Special blood collection tubes.',
    duration: '15 mins',
    reportDelivery: '72 Hours',
    popular: true
  },
  {
    id: 'lab-thyroid-profile-t3-t4-tsh',
    name: 'Thyroid Profile Total (T3, T4, TSH) (A37)',
    category: 'lab',
    subCategory: 'Hormone Assays',
    price: 700,
    discountPrice: 600,
    description: 'CLIA quantitative measurement of Total T3, Total T4, and TSH.',
    preparation: 'Morning sample preferred.',
    duration: '5 mins',
    reportDelivery: '6 Hours',
    popular: true
  },
  {
    id: 'lab-total-cholesterol',
    name: 'Total Cholesterol (A133)',
    category: 'lab',
    subCategory: 'Cardiac Markers',
    price: 200,
    discountPrice: 130,
    description: 'Photometry measurement of serum total cholesterol concentration.',
    preparation: '10-12 hours fasting required.',
    duration: '5 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-total-protein-albumin-globulin',
    name: 'Total Protein & Albumin / Globulin Ratio (A183)',
    category: 'lab',
    subCategory: 'Organ Screeners',
    price: 200,
    discountPrice: 150,
    description: 'Photometry measurement of Serum Total Protein, Albumin, Globulin, and A/G Ratio.',
    preparation: 'No fasting required.',
    duration: '5 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-transferrin-serum',
    name: 'Transferrin (A58)',
    category: 'lab',
    subCategory: 'General Blood Tests',
    price: 1000,
    discountPrice: 600,
    description: 'Nephelometry measurement of iron transport protein Transferrin.',
    preparation: 'Fasting preferred.',
    duration: '10 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-troponin-i-quantitative',
    name: 'Troponin-I (Quantitative Cardiac Marker) (A72)',
    category: 'lab',
    subCategory: 'Cardiac Markers',
    price: 1500,
    discountPrice: 1000,
    description: 'CLIA high-sensitivity Troponin-I assay to rule out acute myocardial infarction.',
    preparation: 'Emergency biomarker, no fasting.',
    duration: '10 mins',
    reportDelivery: '6 Hours',
    popular: true
  },
  {
    id: 'lab-troponin-t-quantitative',
    name: 'Troponin-T (Quantitative Cardiac Marker) (A38)',
    category: 'lab',
    subCategory: 'Cardiac Markers',
    price: 1200,
    discountPrice: 1000,
    description: 'CLIA quantitative measurement of Cardiac Troponin-T.',
    preparation: 'Emergency biomarker.',
    duration: '10 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-typhi-dot-igm-igg',
    name: 'Typhi Dot IgM/IgG (A179)',
    category: 'lab',
    subCategory: 'Infectious Diseases',
    price: 450,
    discountPrice: 300,
    description: 'ELISA screening for Outer Membrane Protein (OMP) antibodies of Salmonella Typhi.',
    preparation: 'No fasting required.',
    duration: '10 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-uric-acid-serum',
    name: 'Serum Uric Acid (A173)',
    category: 'lab',
    subCategory: 'Organ Screeners',
    price: 250,
    discountPrice: 150,
    description: 'Photometry quantitative measurement of Serum Uric Acid for Gout and kidney screening.',
    preparation: 'Fasting preferred.',
    duration: '5 mins',
    reportDelivery: '72 Hours'
  },
  {
    id: 'lab-vdrl-syphilis',
    name: 'VDRL / Syphilis Flocculation Test (A337)',
    category: 'lab',
    subCategory: 'Infectious Diseases',
    price: 400,
    discountPrice: 250,
    description: 'Flocculation screening test for Treponema pallidum / Syphilis antibody.',
    preparation: 'No fasting required.',
    duration: '5 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-vitamin-a-lcms',
    name: 'Vitamin A (Retinol) (A338)',
    category: 'lab',
    subCategory: 'Vitamins & Minerals',
    price: 2500,
    discountPrice: 1850,
    description: 'LC-MS/MS precision measurement of Serum Vitamin A.',
    preparation: '10 hours fasting required.',
    duration: '10 mins',
    reportDelivery: '8 Hours'
  },
  {
    id: 'lab-vitamin-e-lcms',
    name: 'Vitamin E (Tocopherol) (A123)',
    category: 'lab',
    subCategory: 'Vitamins & Minerals',
    price: 2200,
    discountPrice: 1850,
    description: 'LC-MS/MS measurement of Serum Vitamin E antioxidant level.',
    preparation: '10 hours fasting required.',
    duration: '10 mins',
    reportDelivery: '8 Hours'
  },
  {
    id: 'lab-vitamin-k-lcms',
    name: 'Vitamin K (Phylloquinone) (A431)',
    category: 'lab',
    subCategory: 'Vitamins & Minerals',
    price: 2200,
    discountPrice: 1850,
    description: 'LC-MS/MS assay for Vitamin K level.',
    preparation: '10 hours fasting required.',
    duration: '10 mins',
    reportDelivery: '8 Hours'
  },
  {
    id: 'lab-vldl-cholesterol',
    name: 'VLDL Cholesterol (A429)',
    category: 'lab',
    subCategory: 'Cardiac Markers',
    price: 200,
    discountPrice: 129,
    description: 'Photometry calculation of Very Low-Density Lipoprotein Cholesterol.',
    preparation: '12 hours fasting required.',
    duration: '5 mins',
    reportDelivery: '6 Hours'
  },
  {
    id: 'lab-winter-profile-gold',
    name: 'Winter Profile - GOLD (68 Tests) (A386)',
    category: 'lab',
    subCategory: 'Organ Screeners',
    price: 1800,
    discountPrice: 1200,
    description: 'Seasonal winter health screener for immunity, viral fever, CBC, Vitamin D, and Lipid.',
    preparation: '10 hours fasting required.',
    duration: '15 mins',
    reportDelivery: '12 Hours'
  },
  {
    id: 'lab-winter-profile-diamond',
    name: 'Winter Profile - DIAMOND (101 Tests) (A387)',
    category: 'lab',
    subCategory: 'Organ Screeners',
    price: 3000,
    discountPrice: 2000,
    description: 'Master winter profile covering 101 parameters including full organ screeners and immunity markers.',
    preparation: '10 hours fasting required.',
    duration: '15 mins',
    reportDelivery: '12 Hours'
  },
  {
    id: 'lab-women-basic-profile',
    name: 'Women Basic Profile (A133)',
    category: 'lab',
    subCategory: 'Organ Screeners',
    price: 3000,
    discountPrice: 1700,
    description: 'Tailored health checkup for women evaluating CBC, Thyroid, Calcium, Iron, and Urine Routine.',
    preparation: '10 hours fasting required.',
    duration: '15 mins',
    reportDelivery: '12 Hours'
  },
  {
    id: 'lab-women-advanced-profile',
    name: 'Women Advanced Profile (A302)',
    category: 'lab',
    subCategory: 'Organ Screeners',
    price: 3500,
    discountPrice: 2200,
    description: 'Comprehensive wellness profile for women including hormones (FSH, LH, Prolactin), Thyroid, Vitamins, and Bone Density markers.',
    preparation: '10 hours fasting required.',
    duration: '15 mins',
    reportDelivery: '12 Hours',
    popular: true
  }
];

export const HEALTH_PACKAGES: HealthPackage[] = [
  {
    id: 'pkg-sexual-health-basic',
    name: 'Sexual Health Package - Basic',
    price: 2500,
    discountPrice: 1250,
    description: 'Basic sexual health screening package covering major STI/STD markers and general blood count.',
    testsCount: 6,
    includedTests: [
      'HIV 1&2',
      'HbsAg',
      'Anti-HCV',
      'VDRL',
      'CBC',
      'Chlamydia IgG'
    ],
    idealFor: 'Adults seeking essential screening for common sexually transmitted infections.',
    frequency: 'As Needed / Annual',
    preparation: 'No specific fasting required.',
    popular: true
  },
  {
    id: 'pkg-sexual-health-pro',
    name: 'Sexual Health Package - Pro',
    price: 9500,
    discountPrice: 5500,
    description: 'Advanced comprehensive sexual health package testing for complete STI panel, antibodies, and immune cell status.',
    testsCount: 9,
    includedTests: [
      'HIV 1&2',
      'HBSAG',
      'ANTI-HCV',
      'VDRL',
      'Anti Chlamydia IgM',
      'Anti Chlamydia IgG',
      'HSV I & II (IgM+IgG)',
      'TPHA & TP Antibody',
      'CD3, CD4, CD8'
    ],
    idealFor: 'Adults needing a complete diagnostic panel for sexual health and viral/bacterial markers.',
    frequency: 'As Needed',
    preparation: 'No specific preparation required.',
    popular: false
  },
  {
    id: 'pkg-fever-profile',
    name: 'Fever Profile',
    price: 3000,
    discountPrice: 1700,
    description: 'Screening profile to diagnose underlying causes of acute or persistent fever including malaria, dengue, typhoid, and infection markers.',
    testsCount: 7,
    includedTests: [
      'CBC WITH ESR',
      'CRP',
      'WIDAL TEST',
      'MALARIA TEST',
      'URINE R/M/E',
      'DENGUE AG/AB',
      'DENGUE NS1'
    ],
    idealFor: 'Individuals experiencing acute fever, chills, body pain, or seasonal infection symptoms.',
    frequency: 'Immediate / On Symptoms',
    preparation: 'No fasting required.',
    popular: true
  },
  {
    id: 'pkg-sugar-profile',
    name: 'Sugar Profile',
    price: 2000,
    discountPrice: 1000,
    description: 'Comprehensive diabetic profile testing blood glucose, long-term glycemic control, insulin, kidney function, and lipids.',
    testsCount: 6,
    includedTests: [
      'FBS (Fasting Blood Sugar)',
      'PPBS (Post Prandial Blood Sugar)',
      'HbA1c',
      'Insulin',
      'Creatinine',
      'Triglycerides'
    ],
    idealFor: 'Diabetic & pre-diabetic patients, or those with family history of diabetes.',
    frequency: 'Every 3 to 6 Months',
    preparation: '8-10 hours fasting required for FBS, followed by sample 2 hours after meals for PPBS.',
    popular: true
  },
  {
    id: 'pkg-health-econo-plus',
    name: 'Comprehensive Health Package - ECONO +',
    price: 1200,
    discountPrice: 500,
    description: 'Economical entry-level health screening covering essential blood count, blood sugar, renal function, cholesterol, and urine parameters.',
    testsCount: 5,
    includedTests: [
      'Blood Sugar',
      'Serum Cholesterol',
      'Serum Creatinine',
      'Urine R/M/E',
      'Complete Blood Count'
    ],
    idealFor: 'Routine basic health checkup for all age groups.',
    frequency: 'Every 6 Months',
    preparation: '8-10 hours fasting required.',
    popular: true
  },
  {
    id: 'pkg-health-gold',
    name: 'Comprehensive Health Package - GOLD',
    price: 3500,
    discountPrice: 1500,
    description: 'Popular full-body checkup covering blood count, diabetes, liver, kidney, thyroid, lipid profile, and urine routine.',
    testsCount: 8,
    includedTests: [
      'Complete Blood Count',
      'Blood Sugar',
      'Lipid Profile',
      'Liver Function Test',
      'Thyroid Profile',
      'Kidney Function Test',
      'HbA1C with Graph',
      'Urine R/M/E'
    ],
    idealFor: 'Adults looking for thorough annual preventive health checkup.',
    frequency: 'Annually',
    preparation: '10-12 hours overnight fasting required.',
    popular: true
  },
  {
    id: 'pkg-health-platinum',
    name: 'Comprehensive Health Package - PLATINUM',
    price: 4800,
    discountPrice: 2250,
    description: 'Extended health screening adding key vitamins (Vitamin D & B12) and electrolytes to Gold package parameters.',
    testsCount: 11,
    includedTests: [
      'Complete Blood Count',
      'Blood Sugar',
      'Vitamin D',
      'Vitamin B12',
      'Lipid Profile',
      'Liver Function Test',
      'Thyroid Profile',
      'Electrolytes',
      'Kidney Function Test',
      'HbA1C with Graph',
      'Urine R/M/E'
    ],
    idealFor: 'Adults and working professionals needing deep metabolic and vitamin assessment.',
    frequency: 'Annually',
    preparation: '10-12 hours overnight fasting required.',
    popular: true
  },
  {
    id: 'pkg-health-platinum-plus',
    name: 'Health Package - PLATINUM +',
    price: 5200,
    discountPrice: 2500,
    description: 'All-inclusive full-body checkup adding complete Iron Profile along with vitamins, organ panels, and HbA1c.',
    testsCount: 12,
    includedTests: [
      'Complete Blood Count',
      'Blood Sugar (FBS+PPBS)',
      'Vitamin D',
      'Vitamin B12',
      'Lipid Profile',
      'Liver Function Test',
      'Thyroid Profile',
      'Electrolytes',
      'Kidney Function Test',
      'HbA1C with Graph',
      'Urine R/M/E',
      'IRON PROFILE'
    ],
    idealFor: 'Individuals wanting full body evaluation including anemia and iron storage markers.',
    frequency: 'Annually',
    preparation: '10-12 hours overnight fasting required.',
    popular: true
  },
  {
    id: 'pkg-health-ultimate',
    name: 'Health Package - ULTIMATE',
    price: 6500,
    discountPrice: 3200,
    description: 'Ultimate diagnostic suite including cardiac markers, joint markers (RA factor, ESR, CRP), iron profile, vitamins, and organ function tests.',
    testsCount: 15,
    includedTests: [
      'Complete Blood Count',
      'Blood Sugar',
      'Vitamin D',
      'Vitamin B12',
      'Lipid Profile',
      'Liver Function Test',
      'Thyroid Profile',
      'Electrolytes',
      'Kidney Function Test',
      'HbA1C',
      'Iron Profile',
      'RA Factor',
      'ESR',
      'CRP',
      'Cardiac Markers'
    ],
    idealFor: 'Comprehensive body scan for senior adults, executives, or individuals with chronic symptoms.',
    frequency: 'Annually',
    preparation: '10-12 hours overnight fasting required.',
    popular: true
  },
  {
    id: 'pkg-womens-health-essential',
    name: "Women's Health - ESSENTIAL",
    price: 5000,
    discountPrice: 2500,
    description: 'Essential hormonal and metabolic checkup tailored for women covering thyroid, female reproductive hormones, calcium, and blood count.',
    testsCount: 11,
    includedTests: [
      'Blood Sugar',
      'FSH',
      'Prolactin',
      'LH',
      'Estradiol E2',
      'Progesterone',
      'Serum Calcium',
      'HbA1c With Graph',
      'Free Thyroid Function Test (FT3,FT4,TSH)',
      'Complete Blood Count',
      'Serum Iron'
    ],
    idealFor: 'Women of all ages screening for hormonal balance, menstrual irregularities, or fatigue.',
    frequency: 'Annually',
    preparation: 'Overnight fasting required.',
    popular: true
  },
  {
    id: 'pkg-womens-health-advance',
    name: "Women's Health - ADVANCE",
    price: 8500,
    discountPrice: 4500,
    description: "Advanced women's health panel including detailed androgen profile (Testosterone, DHEAS), Beta HCG, Ferritin, SGPT/SGOT, and complete iron profile.",
    testsCount: 17,
    includedTests: [
      'Blood Sugar',
      'FSH',
      'Prolactin',
      'LH',
      'Estradiol E2',
      'Progesterone',
      'Serum Calcium',
      'HbA1c With Graph',
      'Free Thyroid Function Test (FT3,FT4,TSH)',
      'Complete Blood Count',
      'Iron Profile',
      'Total Testosterone',
      'Beta HCG',
      'DHEAS',
      'Ferritin',
      'SGPT, SGOT'
    ],
    idealFor: 'Women seeking full gynecological, hormonal, PCOD/PCOS, and metabolic health evaluation.',
    frequency: 'Annually',
    preparation: 'Overnight fasting required.',
    popular: false
  },
  {
    id: 'pkg-pain-management',
    name: 'Pain Management Package',
    price: 6800,
    discountPrice: 3450,
    description: 'Specialized diagnostic panel for investigating joint pain, arthritis, autoimmune markers (ANA, Anti-CCP, RA factor), bone minerals, and kidney function.',
    testsCount: 12,
    includedTests: [
      'VITAMIN D',
      'VITAMIN B12',
      'CALCITONIN',
      'CALCIUM',
      'RA FACTOR',
      'URIC ACID',
      'ANA',
      'ANTI-CCP',
      'CBC & ESR',
      'CRP',
      'KFT',
      'ELECTROLYTE'
    ],
    idealFor: 'Patients experiencing joint pain, arthritis, swelling, muscle soreness, or autoimmune symptoms.',
    frequency: 'As Advised by Physician',
    preparation: 'No specific fasting needed, morning sample preferred.',
    popular: false
  },
  {
    id: 'pkg-anemia-screening',
    name: 'Anemia Screening Package',
    price: 3500,
    discountPrice: 1700,
    description: 'Targeted screening package for diagnosing causes of anemia, low hemoglobin, ferritin levels, hemoglobinopathies, and liver function.',
    testsCount: 8,
    includedTests: [
      'FASTING BLOOD',
      'COMPLETE HEMOGRAM & ESR',
      'IRON PROFILE',
      'Hb-ELECTROFORESIS',
      'PERIPHERAL BLOOD',
      'FERRITIN',
      'LIVER FUNCTION TEST',
      'AMYLASE-LIPASE'
    ],
    idealFor: 'Patients with persistent fatigue, pale skin, weakness, or unexplained low hemoglobin.',
    frequency: 'As Needed',
    preparation: 'Fasting blood sample required.',
    popular: false
  },
  {
    id: 'pkg-pre-operative',
    name: 'Pre-Operative Package',
    price: 5000,
    discountPrice: 2700,
    description: 'Essential diagnostic pre-surgical clearance profile testing blood coagulation, viral markers, blood grouping, organ function, and ECG.',
    testsCount: 11,
    includedTests: [
      'CBC+ESR',
      'FBS , PPBS',
      'PT - INR',
      'HIV 1 & 2, ECG',
      'HBsAg',
      'ANTI - HCV',
      'RFT',
      'ABO GROUP',
      'BT-CT',
      'ELECTROLYTES',
      'LIVER FUNCTION TEST'
    ],
    idealFor: 'Patients scheduled for surgery or medical procedures requiring pre-op clearance.',
    frequency: 'Before Surgery',
    preparation: 'Overnight fasting required.',
    popular: false
  },
  {
    id: 'pkg-cardiac-profile',
    name: 'Cardiac Profile',
    price: 5800,
    discountPrice: 3000,
    description: 'Comprehensive cardiac screening assessing heart muscle markers (Trop I, CPK, CK-MB), blood sugar, ECG, D-Dimer, and liver/cardiac enzymes.',
    testsCount: 7,
    includedTests: [
      'FBS , PPBS',
      'CBC, ECG',
      'CPK',
      'CK - MB',
      'TROP I',
      'D-DIMER',
      'SGOT , LDH'
    ],
    idealFor: 'Individuals experiencing chest discomfort, breathlessness, hypertension, or heart risk monitoring.',
    frequency: 'As Needed / Annually',
    preparation: 'Fasting sample required.',
    popular: true
  },
  {
    id: 'pkg-infertility-profile',
    name: 'Infertility Profile (Male & Female)',
    price: 9800,
    discountPrice: 4950,
    description: 'Complete reproductive and fertility evaluation panel for couples, covering male and female hormonal panels and semen analysis.',
    testsCount: 17,
    includedTests: [
      'Female Panel: FBS, CBC, FSH, LH, Estradiol, Progesterone, Prolactin, SGPT, Thyroid Profile, Urine R/M/E',
      'Male Panel: FBS, CBC, FSH, LH, Prolactin, Testosterone (Free & Total), Semen Analysis'
    ],
    idealFor: 'Couples planning pregnancy or evaluating fertility health.',
    frequency: 'As Needed',
    preparation: 'Specific cycle day timing for females and 3-5 days abstinence for semen analysis.',
    popular: false
  },
  {
    id: 'pkg-hair-loss-profile',
    name: 'Hair Loss Profile',
    price: 8900,
    discountPrice: 4750,
    description: 'Specialized diagnostic panel for identifying root causes of alopecia and excessive hair fall, evaluating hormones, thyroid, biotin, and androgen status.',
    testsCount: 10,
    includedTests: [
      'FSH',
      'PROLACTIN',
      'LH',
      'FASTING INSULIN',
      'ESTRADIOL',
      'TESTOSTERONE (FREE AND TOTAL)',
      'SEX HORMONE BINDING GLOBULIN (SHBG)',
      'BIOTIN',
      'THYROID PROFILE',
      'DHEAS'
    ],
    idealFor: 'Men and women experiencing severe hair thinning, hair loss, or scalp issues.',
    frequency: 'As Needed',
    preparation: 'Fasting blood sample required.',
    popular: false
  }
];

export const FREQUENT_QUESTIONS = [
  {
    q: "Why are your rates significantly lower than other diagnostic centers?",
    a: "At AssurX, our mission is to make high-quality, trusted diagnostics affordable for every Indian. By utilizing high-throughput, state-of-the-art robotic machines in our centralized NABL labs and reducing administrative overheads, we pass 100% of the cost savings directly to our patients. We offer the exact same diagnostic accuracy and technology at up to 50% lower prices."
  },
  {
    q: "How does the Home Sample Collection service work?",
    a: "Once you book a blood test or health package and choose 'Home Collection', a certified, experienced medical Phlebotomist is assigned to your booking. They will visit your home at your chosen time slot, extract samples using sterile vacuum tubes, store them immediately in cold-chain transport boxes, and safely deliver them to our laboratory. Home collection is free or has a very nominal charge depending on your booking."
  },
  {
    q: "How and when will I get my diagnostic reports?",
    a: "Our diagnostic lab systems are highly automated. As soon as your report is ready, certified, and digitally signed by our doctors, you will receive an SMS and WhatsApp notification with a link. You can also view and download all historical reports instantly by logging into your Patient Portal/Dashboard on this website using your registered mobile number."
  },
  {
    q: "Are AssurX Scans and Lab reports valid in all hospitals?",
    a: "Absolutely! All AssurX laboratory reports are generated from NABL-accredited, state-of-the-art facilities and comply strictly with ISO standards. All scan images (MRI, CT, Ultrasound) are read and reported by highly experienced MD Radiologists. Our reports are 100% trusted and accepted by all major hospitals, clinicians, and health insurance providers across India."
  },
  {
    q: "What is the preparation required for an MRI or CT Scan?",
    a: "For general MRI, ensure no metal accessories are worn. For CT Whole Abdomen/Contrast scans or Whole Abdomen Ultrasounds, fasting for 6 hours is mandatory. For contrast CT scans, a recent Serum Creatinine lab report is required to verify kidney safety. Specific instructions for your booked test are shown clearly on your digital booking confirmation."
  }
];

export const CUSTOMER_TESTIMONIALS: Testimonial[] = [
  {
    id: 't-1',
    name: "Rajesh Kumar",
    rating: 5,
    comment: "Excellent experience. Booked an USG scan for my father. Staff was very polite and supportive. MD Radiologist report was ready within 2 hours. Best diagnostic center in Malad with affordable rates!",
    location: "Malad West, Mumbai",
    date: "12 days ago"
  },
  {
    id: 't-2',
    name: "Sneha Deshmukh",
    rating: 5,
    comment: "The Phlebotomist arrived right on time for the Home Blood Collection. He was highly skilled, used sterile sealed equipment, and took the sample painless. Got accurate digital reports on WhatsApp the same evening!",
    location: "Goregaon East, Mumbai",
    date: "1 week ago"
  },
  {
    id: 't-3',
    name: "Amit Patel",
    rating: 5,
    comment: "Very neat, clean, and modern diagnostic center with high-tech equipment. Extremely polite staff and seamless online booking. Highly recommended for all ultrasound scans and blood checkups!",
    location: "Malad East, Mumbai",
    date: "3 days ago"
  }
];

export const ASSURX_CENTERS = [
  { city: "Malad", address: "Shop 1-3, SV Road, Opp. Malad Railway Station, Malad West, Mumbai - 400064", phone: "022-50117701" },
  { city: "Goregaon", address: "G-4, Sun Plaza, SV Road, Near Goregaon East Metro, Goregaon, Mumbai - 400063", phone: "022-50117702" }
];
